import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
const folder = new URL('../src/data/labs/', import.meta.url);
const names = readdirSync(folder).filter(name => name.endsWith('.json')).sort();
const ids = new Set();
for (const name of names) {
  const ref = JSON.parse(readFileSync(new URL(name, folder), 'utf8'));
  if (!ref.id || !ref.title || !Array.isArray(ref.nodes) || !Array.isArray(ref.edges)) throw new Error(`Invalid lab reference: ${name}`);
  if (ids.has(ref.id)) throw new Error(`Duplicate lab reference ID: ${ref.id}`);
  ids.add(ref.id);
}
const source = '// Generated by scripts/generate-labs.mjs. Add lab reference JSON files to labs/.\n'
  + "import type { LabReference } from './courseLabShared.ts';\n"
  + names.map((name, i) => `import labRef${i} from ${JSON.stringify(`./labs/${name}`)} with { type: 'json' };`).join('\n')
  + '\nexport const LAB_REFERENCES = [' + names.map((_, i) => `labRef${i}`).join(', ') + '] as LabReference[];\n';
writeFileSync(new URL('../src/data/labsRegistry.ts', import.meta.url), source);
